# Generated by Django 3.2.13 on 2024-08-11 01:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='詳細')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnail/', verbose_name='画像')),
                ('movie', models.FileField(blank=True, null=True, upload_to='media/uploads/%Y/%m/%d/', verbose_name='動画')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('good', models.IntegerField(default=0, verbose_name='高評価')),
                ('read', models.IntegerField(default=0, verbose_name='閲覧数')),
                ('usertext', models.CharField(default='a', max_length=50)),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('good', models.IntegerField(default=0, verbose_name='いいね')),
                ('usertext', models.CharField(default='a', max_length=30)),
                ('username', models.CharField(default='a', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='youtube.post', verbose_name='紐付け')),
            ],
        ),
    ]
